/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 37.0.1 Fri Dec 24 21:22:54 2021.
 */

#include <string.h>

#include "dbc_rms.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int dbc_rms_m173_modulation_and_flux_info::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m173_modulation_and_flux_info_t *src_p,
    size_t size)
{
    uint16_t d1_modulation_index;
    uint16_t d2_flux_weakening_output;
    uint16_t d3_id_command;
    uint16_t d4_iq_command;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    d1_modulation_index = (uint16_t)src_p->d1_modulation_index;
    dst_p[0] |= pack_left_shift_u16(d1_modulation_index, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(d1_modulation_index, 8u, 0xffu);
    d2_flux_weakening_output = (uint16_t)src_p->d2_flux_weakening_output;
    dst_p[2] |= pack_left_shift_u16(d2_flux_weakening_output, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(d2_flux_weakening_output, 8u, 0xffu);
    d3_id_command = (uint16_t)src_p->d3_id_command;
    dst_p[4] |= pack_left_shift_u16(d3_id_command, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(d3_id_command, 8u, 0xffu);
    d4_iq_command = (uint16_t)src_p->d4_iq_command;
    dst_p[6] |= pack_left_shift_u16(d4_iq_command, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(d4_iq_command, 8u, 0xffu);

    return (8);
}

int dbc_rms_m173_modulation_and_flux_info::unpack(
    struct dbc_rms_m173_modulation_and_flux_info_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t d1_modulation_index;
    uint16_t d2_flux_weakening_output;
    uint16_t d3_id_command;
    uint16_t d4_iq_command;

    if (size < 8u) {
        return (-EINVAL);
    }

    d1_modulation_index = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    d1_modulation_index |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d1_modulation_index = (int16_t)d1_modulation_index;
    d2_flux_weakening_output = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    d2_flux_weakening_output |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->d2_flux_weakening_output = (int16_t)d2_flux_weakening_output;
    d3_id_command = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    d3_id_command |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->d3_id_command = (int16_t)d3_id_command;
    d4_iq_command = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    d4_iq_command |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->d4_iq_command = (int16_t)d4_iq_command;

    return (0);
}

int16_t dbc_rms_m173_modulation_and_flux_info::d1_modulation_index_encode(double value)
{
    return (int16_t)(value / 0.0001);
}

double dbc_rms_m173_modulation_and_flux_info::d1_modulation_index_decode(int16_t value)
{
    return ((double)value * 0.0001);
}

bool dbc_rms_m173_modulation_and_flux_info::d1_modulation_index_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m173_modulation_and_flux_info::d2_flux_weakening_output_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m173_modulation_and_flux_info::d2_flux_weakening_output_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m173_modulation_and_flux_info::d2_flux_weakening_output_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m173_modulation_and_flux_info::d3_id_command_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m173_modulation_and_flux_info::d3_id_command_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m173_modulation_and_flux_info::d3_id_command_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m173_modulation_and_flux_info::d4_iq_command_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m173_modulation_and_flux_info::d4_iq_command_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m173_modulation_and_flux_info::d4_iq_command_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int dbc_rms_m172_torque_and_timer_info::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m172_torque_and_timer_info_t *src_p,
    size_t size)
{
    uint16_t d1_commanded_torque;
    uint16_t d2_torque_feedback;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    d1_commanded_torque = (uint16_t)src_p->d1_commanded_torque;
    dst_p[0] |= pack_left_shift_u16(d1_commanded_torque, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(d1_commanded_torque, 8u, 0xffu);
    d2_torque_feedback = (uint16_t)src_p->d2_torque_feedback;
    dst_p[2] |= pack_left_shift_u16(d2_torque_feedback, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(d2_torque_feedback, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->d3_power_on_timer, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->d3_power_on_timer, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->d3_power_on_timer, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->d3_power_on_timer, 24u, 0xffu);

    return (8);
}

int dbc_rms_m172_torque_and_timer_info::unpack(
    struct dbc_rms_m172_torque_and_timer_info_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t d1_commanded_torque;
    uint16_t d2_torque_feedback;

    if (size < 8u) {
        return (-EINVAL);
    }

    d1_commanded_torque = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    d1_commanded_torque |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d1_commanded_torque = (int16_t)d1_commanded_torque;
    d2_torque_feedback = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    d2_torque_feedback |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->d2_torque_feedback = (int16_t)d2_torque_feedback;
    dst_p->d3_power_on_timer = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->d3_power_on_timer |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->d3_power_on_timer |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->d3_power_on_timer |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int16_t dbc_rms_m172_torque_and_timer_info::d1_commanded_torque_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m172_torque_and_timer_info::d1_commanded_torque_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m172_torque_and_timer_info::d1_commanded_torque_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m172_torque_and_timer_info::d2_torque_feedback_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m172_torque_and_timer_info::d2_torque_feedback_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m172_torque_and_timer_info::d2_torque_feedback_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint32_t dbc_rms_m172_torque_and_timer_info::d3_power_on_timer_encode(double value)
{
    return (uint32_t)(value / 0.003);
}

double dbc_rms_m172_torque_and_timer_info::d3_power_on_timer_decode(uint32_t value)
{
    return ((double)value * 0.003);
}

bool dbc_rms_m172_torque_and_timer_info::d3_power_on_timer_is_in_range(uint32_t value)
{
    return (value <= 4294933333u);
}

int dbc_rms_m194_read_write_param_response::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m194_read_write_param_response_t *src_p,
    size_t size)
{
    uint16_t d3_data_response;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->d1_parameter_address_response, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->d1_parameter_address_response, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->d2_write_success, 0u, 0x01u);
    d3_data_response = (uint16_t)src_p->d3_data_response;
    dst_p[4] |= pack_left_shift_u16(d3_data_response, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(d3_data_response, 8u, 0xffu);

    return (8);
}

int dbc_rms_m194_read_write_param_response::unpack(
    struct dbc_rms_m194_read_write_param_response_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t d3_data_response;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->d1_parameter_address_response = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->d1_parameter_address_response |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d2_write_success = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    d3_data_response = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    d3_data_response |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->d3_data_response = (int16_t)d3_data_response;

    return (0);
}

uint16_t dbc_rms_m194_read_write_param_response::d1_parameter_address_response_encode(double value)
{
    return (uint16_t)(value);
}

double dbc_rms_m194_read_write_param_response::d1_parameter_address_response_decode(uint16_t value)
{
    return ((double)value);
}

bool dbc_rms_m194_read_write_param_response::d1_parameter_address_response_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t dbc_rms_m194_read_write_param_response::d2_write_success_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m194_read_write_param_response::d2_write_success_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m194_read_write_param_response::d2_write_success_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int16_t dbc_rms_m194_read_write_param_response::d3_data_response_encode(double value)
{
    return (int16_t)(value);
}

double dbc_rms_m194_read_write_param_response::d3_data_response_decode(int16_t value)
{
    return ((double)value);
}

bool dbc_rms_m194_read_write_param_response::d3_data_response_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int dbc_rms_m193_read_write_param_command::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m193_read_write_param_command_t *src_p,
    size_t size)
{
    uint16_t d3_data_command;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->d1_parameter_address_command, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->d1_parameter_address_command, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->d2_read_write_command, 0u, 0x01u);
    d3_data_command = (uint16_t)src_p->d3_data_command;
    dst_p[4] |= pack_left_shift_u16(d3_data_command, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(d3_data_command, 8u, 0xffu);

    return (8);
}

int dbc_rms_m193_read_write_param_command::unpack(
    struct dbc_rms_m193_read_write_param_command_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t d3_data_command;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->d1_parameter_address_command = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->d1_parameter_address_command |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d2_read_write_command = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    d3_data_command = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    d3_data_command |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->d3_data_command = (int16_t)d3_data_command;

    return (0);
}

uint16_t dbc_rms_m193_read_write_param_command::d1_parameter_address_command_encode(double value)
{
    return (uint16_t)(value);
}

double dbc_rms_m193_read_write_param_command::d1_parameter_address_command_decode(uint16_t value)
{
    return ((double)value);
}

bool dbc_rms_m193_read_write_param_command::d1_parameter_address_command_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t dbc_rms_m193_read_write_param_command::d2_read_write_command_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m193_read_write_param_command::d2_read_write_command_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m193_read_write_param_command::d2_read_write_command_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int16_t dbc_rms_m193_read_write_param_command::d3_data_command_encode(double value)
{
    return (int16_t)(value);
}

double dbc_rms_m193_read_write_param_command::d3_data_command_decode(int16_t value)
{
    return ((double)value);
}

bool dbc_rms_m193_read_write_param_command::d3_data_command_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int dbc_rms_m192_command_message::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m192_command_message_t *src_p,
    size_t size)
{
    uint16_t speed_command;
    uint16_t torque_command;
    uint16_t torque_limit_command;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    torque_command = (uint16_t)src_p->torque_command;
    dst_p[0] |= pack_left_shift_u16(torque_command, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(torque_command, 8u, 0xffu);
    speed_command = (uint16_t)src_p->speed_command;
    dst_p[2] |= pack_left_shift_u16(speed_command, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(speed_command, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->direction_command, 0u, 0x01u);
    dst_p[5] |= pack_left_shift_u8(src_p->inverter_enable, 0u, 0x01u);
    dst_p[5] |= pack_left_shift_u8(src_p->inverter_discharge, 1u, 0x02u);
    dst_p[5] |= pack_left_shift_u8(src_p->speed_mode_enable, 2u, 0x04u);
    dst_p[5] |= pack_left_shift_u8(src_p->rolling_counter, 4u, 0xf0u);
    torque_limit_command = (uint16_t)src_p->torque_limit_command;
    dst_p[6] |= pack_left_shift_u16(torque_limit_command, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(torque_limit_command, 8u, 0xffu);

    return (8);
}

int dbc_rms_m192_command_message::unpack(
    struct dbc_rms_m192_command_message_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t speed_command;
    uint16_t torque_command;
    uint16_t torque_limit_command;

    if (size < 8u) {
        return (-EINVAL);
    }

    torque_command = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    torque_command |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->torque_command = (int16_t)torque_command;
    speed_command = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    speed_command |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->speed_command = (int16_t)speed_command;
    dst_p->direction_command = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->inverter_enable = unpack_right_shift_u8(src_p[5], 0u, 0x01u);
    dst_p->inverter_discharge = unpack_right_shift_u8(src_p[5], 1u, 0x02u);
    dst_p->speed_mode_enable = unpack_right_shift_u8(src_p[5], 2u, 0x04u);
    dst_p->rolling_counter = unpack_right_shift_u8(src_p[5], 4u, 0xf0u);
    torque_limit_command = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    torque_limit_command |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->torque_limit_command = (int16_t)torque_limit_command;

    return (0);
}

int16_t dbc_rms_m192_command_message::torque_command_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m192_command_message::torque_command_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m192_command_message::torque_command_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m192_command_message::speed_command_encode(double value)
{
    return (int16_t)(value);
}

double dbc_rms_m192_command_message::speed_command_decode(int16_t value)
{
    return ((double)value);
}

bool dbc_rms_m192_command_message::speed_command_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint8_t dbc_rms_m192_command_message::direction_command_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m192_command_message::direction_command_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m192_command_message::direction_command_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m192_command_message::inverter_enable_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m192_command_message::inverter_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m192_command_message::inverter_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m192_command_message::inverter_discharge_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m192_command_message::inverter_discharge_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m192_command_message::inverter_discharge_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m192_command_message::speed_mode_enable_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m192_command_message::speed_mode_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m192_command_message::speed_mode_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m192_command_message::rolling_counter_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m192_command_message::rolling_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m192_command_message::rolling_counter_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int16_t dbc_rms_m192_command_message::torque_limit_command_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m192_command_message::torque_limit_command_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m192_command_message::torque_limit_command_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int dbc_rms_m171_fault_codes::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m171_fault_codes_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->d1_post_fault_lo, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->d1_post_fault_lo, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->d2_post_fault_hi, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->d2_post_fault_hi, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->d3_run_fault_lo, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->d3_run_fault_lo, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->d4_run_fault_hi, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->d4_run_fault_hi, 8u, 0xffu);

    return (8);
}

int dbc_rms_m171_fault_codes::unpack(
    struct dbc_rms_m171_fault_codes_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->d1_post_fault_lo = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->d1_post_fault_lo |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d2_post_fault_hi = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->d2_post_fault_hi |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->d3_run_fault_lo = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->d3_run_fault_lo |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->d4_run_fault_hi = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->d4_run_fault_hi |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t dbc_rms_m171_fault_codes::d1_post_fault_lo_encode(double value)
{
    return (uint16_t)(value);
}

double dbc_rms_m171_fault_codes::d1_post_fault_lo_decode(uint16_t value)
{
    return ((double)value);
}

bool dbc_rms_m171_fault_codes::d1_post_fault_lo_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t dbc_rms_m171_fault_codes::d2_post_fault_hi_encode(double value)
{
    return (uint16_t)(value);
}

double dbc_rms_m171_fault_codes::d2_post_fault_hi_decode(uint16_t value)
{
    return ((double)value);
}

bool dbc_rms_m171_fault_codes::d2_post_fault_hi_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t dbc_rms_m171_fault_codes::d3_run_fault_lo_encode(double value)
{
    return (uint16_t)(value);
}

double dbc_rms_m171_fault_codes::d3_run_fault_lo_decode(uint16_t value)
{
    return ((double)value);
}

bool dbc_rms_m171_fault_codes::d3_run_fault_lo_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t dbc_rms_m171_fault_codes::d4_run_fault_hi_encode(double value)
{
    return (uint16_t)(value);
}

double dbc_rms_m171_fault_codes::d4_run_fault_hi_decode(uint16_t value)
{
    return ((double)value);
}

bool dbc_rms_m171_fault_codes::d4_run_fault_hi_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int dbc_rms_m170_internal_states::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m170_internal_states_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->d1_vsm_state, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->d1_pwm_frequency, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->d2_inverter_state, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->d3_relay_1_status, 0u, 0x01u);
    dst_p[3] |= pack_left_shift_u8(src_p->d3_relay_2_status, 1u, 0x02u);
    dst_p[3] |= pack_left_shift_u8(src_p->d3_relay_3_status, 2u, 0x04u);
    dst_p[3] |= pack_left_shift_u8(src_p->d3_relay_4_status, 3u, 0x08u);
    dst_p[3] |= pack_left_shift_u8(src_p->d3_relay_5_status, 4u, 0x10u);
    dst_p[3] |= pack_left_shift_u8(src_p->d3_relay_6_status, 5u, 0x20u);
    dst_p[4] |= pack_left_shift_u8(src_p->d4_inverter_run_mode, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->d4_inverter_discharge_state, 5u, 0xe0u);
    dst_p[5] |= pack_left_shift_u8(src_p->d5_inverter_command_mode, 0u, 0x01u);
    dst_p[5] |= pack_left_shift_u8(src_p->d5_rolling_counter, 4u, 0xf0u);
    dst_p[6] |= pack_left_shift_u8(src_p->d6_inverter_enable_state, 0u, 0x01u);
    dst_p[6] |= pack_left_shift_u8(src_p->d6_inverter_enable_lockout, 7u, 0x80u);
    dst_p[7] |= pack_left_shift_u8(src_p->d7_direction_command, 0u, 0x01u);
    dst_p[7] |= pack_left_shift_u8(src_p->d7_bms_active, 1u, 0x02u);
    dst_p[7] |= pack_left_shift_u8(src_p->d7_bms_torque_limiting, 2u, 0x04u);
    dst_p[7] |= pack_left_shift_u8(src_p->d7_max_speed_limiting, 3u, 0x08u);
    dst_p[7] |= pack_left_shift_u8(src_p->d7_low_speed_limiting, 5u, 0x20u);

    return (8);
}

int dbc_rms_m170_internal_states::unpack(
    struct dbc_rms_m170_internal_states_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->d1_vsm_state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->d1_pwm_frequency = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->d2_inverter_state = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->d3_relay_1_status = unpack_right_shift_u8(src_p[3], 0u, 0x01u);
    dst_p->d3_relay_2_status = unpack_right_shift_u8(src_p[3], 1u, 0x02u);
    dst_p->d3_relay_3_status = unpack_right_shift_u8(src_p[3], 2u, 0x04u);
    dst_p->d3_relay_4_status = unpack_right_shift_u8(src_p[3], 3u, 0x08u);
    dst_p->d3_relay_5_status = unpack_right_shift_u8(src_p[3], 4u, 0x10u);
    dst_p->d3_relay_6_status = unpack_right_shift_u8(src_p[3], 5u, 0x20u);
    dst_p->d4_inverter_run_mode = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->d4_inverter_discharge_state = unpack_right_shift_u8(src_p[4], 5u, 0xe0u);
    dst_p->d5_inverter_command_mode = unpack_right_shift_u8(src_p[5], 0u, 0x01u);
    dst_p->d5_rolling_counter = unpack_right_shift_u8(src_p[5], 4u, 0xf0u);
    dst_p->d6_inverter_enable_state = unpack_right_shift_u8(src_p[6], 0u, 0x01u);
    dst_p->d6_inverter_enable_lockout = unpack_right_shift_u8(src_p[6], 7u, 0x80u);
    dst_p->d7_direction_command = unpack_right_shift_u8(src_p[7], 0u, 0x01u);
    dst_p->d7_bms_active = unpack_right_shift_u8(src_p[7], 1u, 0x02u);
    dst_p->d7_bms_torque_limiting = unpack_right_shift_u8(src_p[7], 2u, 0x04u);
    dst_p->d7_max_speed_limiting = unpack_right_shift_u8(src_p[7], 3u, 0x08u);
    dst_p->d7_low_speed_limiting = unpack_right_shift_u8(src_p[7], 5u, 0x20u);

    return (0);
}

uint8_t dbc_rms_m170_internal_states::d1_vsm_state_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d1_vsm_state_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d1_vsm_state_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t dbc_rms_m170_internal_states::d1_pwm_frequency_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d1_pwm_frequency_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d1_pwm_frequency_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t dbc_rms_m170_internal_states::d2_inverter_state_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d2_inverter_state_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d2_inverter_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t dbc_rms_m170_internal_states::d3_relay_1_status_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d3_relay_1_status_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d3_relay_1_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m170_internal_states::d3_relay_2_status_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d3_relay_2_status_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d3_relay_2_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m170_internal_states::d3_relay_3_status_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d3_relay_3_status_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d3_relay_3_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m170_internal_states::d3_relay_4_status_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d3_relay_4_status_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d3_relay_4_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m170_internal_states::d3_relay_5_status_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d3_relay_5_status_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d3_relay_5_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m170_internal_states::d3_relay_6_status_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d3_relay_6_status_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d3_relay_6_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m170_internal_states::d4_inverter_run_mode_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d4_inverter_run_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d4_inverter_run_mode_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m170_internal_states::d4_inverter_discharge_state_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d4_inverter_discharge_state_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d4_inverter_discharge_state_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t dbc_rms_m170_internal_states::d5_inverter_command_mode_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d5_inverter_command_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d5_inverter_command_mode_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m170_internal_states::d5_rolling_counter_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d5_rolling_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d5_rolling_counter_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t dbc_rms_m170_internal_states::d6_inverter_enable_state_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d6_inverter_enable_state_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d6_inverter_enable_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m170_internal_states::d6_inverter_enable_lockout_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d6_inverter_enable_lockout_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d6_inverter_enable_lockout_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m170_internal_states::d7_direction_command_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d7_direction_command_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d7_direction_command_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m170_internal_states::d7_bms_active_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d7_bms_active_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d7_bms_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m170_internal_states::d7_bms_torque_limiting_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d7_bms_torque_limiting_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d7_bms_torque_limiting_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m170_internal_states::d7_max_speed_limiting_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d7_max_speed_limiting_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d7_max_speed_limiting_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m170_internal_states::d7_low_speed_limiting_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m170_internal_states::d7_low_speed_limiting_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m170_internal_states::d7_low_speed_limiting_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int dbc_rms_m169_internal_voltages::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m169_internal_voltages_t *src_p,
    size_t size)
{
    uint16_t d1_reference_voltage_1_5;
    uint16_t d2_reference_voltage_2_5;
    uint16_t d3_reference_voltage_5_0;
    uint16_t d4_reference_voltage_12_0;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    d1_reference_voltage_1_5 = (uint16_t)src_p->d1_reference_voltage_1_5;
    dst_p[0] |= pack_left_shift_u16(d1_reference_voltage_1_5, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(d1_reference_voltage_1_5, 8u, 0xffu);
    d2_reference_voltage_2_5 = (uint16_t)src_p->d2_reference_voltage_2_5;
    dst_p[2] |= pack_left_shift_u16(d2_reference_voltage_2_5, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(d2_reference_voltage_2_5, 8u, 0xffu);
    d3_reference_voltage_5_0 = (uint16_t)src_p->d3_reference_voltage_5_0;
    dst_p[4] |= pack_left_shift_u16(d3_reference_voltage_5_0, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(d3_reference_voltage_5_0, 8u, 0xffu);
    d4_reference_voltage_12_0 = (uint16_t)src_p->d4_reference_voltage_12_0;
    dst_p[6] |= pack_left_shift_u16(d4_reference_voltage_12_0, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(d4_reference_voltage_12_0, 8u, 0xffu);

    return (8);
}

int dbc_rms_m169_internal_voltages::unpack(
    struct dbc_rms_m169_internal_voltages_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t d1_reference_voltage_1_5;
    uint16_t d2_reference_voltage_2_5;
    uint16_t d3_reference_voltage_5_0;
    uint16_t d4_reference_voltage_12_0;

    if (size < 8u) {
        return (-EINVAL);
    }

    d1_reference_voltage_1_5 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    d1_reference_voltage_1_5 |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d1_reference_voltage_1_5 = (int16_t)d1_reference_voltage_1_5;
    d2_reference_voltage_2_5 = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    d2_reference_voltage_2_5 |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->d2_reference_voltage_2_5 = (int16_t)d2_reference_voltage_2_5;
    d3_reference_voltage_5_0 = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    d3_reference_voltage_5_0 |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->d3_reference_voltage_5_0 = (int16_t)d3_reference_voltage_5_0;
    d4_reference_voltage_12_0 = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    d4_reference_voltage_12_0 |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->d4_reference_voltage_12_0 = (int16_t)d4_reference_voltage_12_0;

    return (0);
}

int16_t dbc_rms_m169_internal_voltages::d1_reference_voltage_1_5_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double dbc_rms_m169_internal_voltages::d1_reference_voltage_1_5_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool dbc_rms_m169_internal_voltages::d1_reference_voltage_1_5_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m169_internal_voltages::d2_reference_voltage_2_5_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double dbc_rms_m169_internal_voltages::d2_reference_voltage_2_5_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool dbc_rms_m169_internal_voltages::d2_reference_voltage_2_5_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m169_internal_voltages::d3_reference_voltage_5_0_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double dbc_rms_m169_internal_voltages::d3_reference_voltage_5_0_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool dbc_rms_m169_internal_voltages::d3_reference_voltage_5_0_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m169_internal_voltages::d4_reference_voltage_12_0_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double dbc_rms_m169_internal_voltages::d4_reference_voltage_12_0_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool dbc_rms_m169_internal_voltages::d4_reference_voltage_12_0_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int dbc_rms_m168_flux_id_iq_info::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m168_flux_id_iq_info_t *src_p,
    size_t size)
{
    uint16_t d1_flux_command;
    uint16_t d2_flux_feedback;
    uint16_t d3_id;
    uint16_t d4_iq;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    d1_flux_command = (uint16_t)src_p->d1_flux_command;
    dst_p[0] |= pack_left_shift_u16(d1_flux_command, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(d1_flux_command, 8u, 0xffu);
    d2_flux_feedback = (uint16_t)src_p->d2_flux_feedback;
    dst_p[2] |= pack_left_shift_u16(d2_flux_feedback, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(d2_flux_feedback, 8u, 0xffu);
    d3_id = (uint16_t)src_p->d3_id;
    dst_p[4] |= pack_left_shift_u16(d3_id, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(d3_id, 8u, 0xffu);
    d4_iq = (uint16_t)src_p->d4_iq;
    dst_p[6] |= pack_left_shift_u16(d4_iq, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(d4_iq, 8u, 0xffu);

    return (8);
}

int dbc_rms_m168_flux_id_iq_info::unpack(
    struct dbc_rms_m168_flux_id_iq_info_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t d1_flux_command;
    uint16_t d2_flux_feedback;
    uint16_t d3_id;
    uint16_t d4_iq;

    if (size < 8u) {
        return (-EINVAL);
    }

    d1_flux_command = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    d1_flux_command |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d1_flux_command = (int16_t)d1_flux_command;
    d2_flux_feedback = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    d2_flux_feedback |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->d2_flux_feedback = (int16_t)d2_flux_feedback;
    d3_id = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    d3_id |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->d3_id = (int16_t)d3_id;
    d4_iq = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    d4_iq |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->d4_iq = (int16_t)d4_iq;

    return (0);
}

int16_t dbc_rms_m168_flux_id_iq_info::d1_flux_command_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double dbc_rms_m168_flux_id_iq_info::d1_flux_command_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool dbc_rms_m168_flux_id_iq_info::d1_flux_command_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m168_flux_id_iq_info::d2_flux_feedback_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double dbc_rms_m168_flux_id_iq_info::d2_flux_feedback_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool dbc_rms_m168_flux_id_iq_info::d2_flux_feedback_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m168_flux_id_iq_info::d3_id_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m168_flux_id_iq_info::d3_id_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m168_flux_id_iq_info::d3_id_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m168_flux_id_iq_info::d4_iq_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m168_flux_id_iq_info::d4_iq_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m168_flux_id_iq_info::d4_iq_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int dbc_rms_m167_voltage_info::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m167_voltage_info_t *src_p,
    size_t size)
{
    uint16_t d1_dc_bus_voltage;
    uint16_t d2_output_voltage;
    uint16_t d3_vab_vd_voltage;
    uint16_t d4_vbc_vq_voltage;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    d1_dc_bus_voltage = (uint16_t)src_p->d1_dc_bus_voltage;
    dst_p[0] |= pack_left_shift_u16(d1_dc_bus_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(d1_dc_bus_voltage, 8u, 0xffu);
    d2_output_voltage = (uint16_t)src_p->d2_output_voltage;
    dst_p[2] |= pack_left_shift_u16(d2_output_voltage, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(d2_output_voltage, 8u, 0xffu);
    d3_vab_vd_voltage = (uint16_t)src_p->d3_vab_vd_voltage;
    dst_p[4] |= pack_left_shift_u16(d3_vab_vd_voltage, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(d3_vab_vd_voltage, 8u, 0xffu);
    d4_vbc_vq_voltage = (uint16_t)src_p->d4_vbc_vq_voltage;
    dst_p[6] |= pack_left_shift_u16(d4_vbc_vq_voltage, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(d4_vbc_vq_voltage, 8u, 0xffu);

    return (8);
}

int dbc_rms_m167_voltage_info::unpack(
    struct dbc_rms_m167_voltage_info_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t d1_dc_bus_voltage;
    uint16_t d2_output_voltage;
    uint16_t d3_vab_vd_voltage;
    uint16_t d4_vbc_vq_voltage;

    if (size < 8u) {
        return (-EINVAL);
    }

    d1_dc_bus_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    d1_dc_bus_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d1_dc_bus_voltage = (int16_t)d1_dc_bus_voltage;
    d2_output_voltage = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    d2_output_voltage |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->d2_output_voltage = (int16_t)d2_output_voltage;
    d3_vab_vd_voltage = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    d3_vab_vd_voltage |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->d3_vab_vd_voltage = (int16_t)d3_vab_vd_voltage;
    d4_vbc_vq_voltage = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    d4_vbc_vq_voltage |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->d4_vbc_vq_voltage = (int16_t)d4_vbc_vq_voltage;

    return (0);
}

int16_t dbc_rms_m167_voltage_info::d1_dc_bus_voltage_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m167_voltage_info::d1_dc_bus_voltage_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m167_voltage_info::d1_dc_bus_voltage_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m167_voltage_info::d2_output_voltage_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m167_voltage_info::d2_output_voltage_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m167_voltage_info::d2_output_voltage_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m167_voltage_info::d3_vab_vd_voltage_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m167_voltage_info::d3_vab_vd_voltage_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m167_voltage_info::d3_vab_vd_voltage_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m167_voltage_info::d4_vbc_vq_voltage_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m167_voltage_info::d4_vbc_vq_voltage_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m167_voltage_info::d4_vbc_vq_voltage_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int dbc_rms_m166_current_info::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m166_current_info_t *src_p,
    size_t size)
{
    uint16_t d1_phase_a_current;
    uint16_t d2_phase_b_current;
    uint16_t d3_phase_c_current;
    uint16_t d4_dc_bus_current;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    d1_phase_a_current = (uint16_t)src_p->d1_phase_a_current;
    dst_p[0] |= pack_left_shift_u16(d1_phase_a_current, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(d1_phase_a_current, 8u, 0xffu);
    d2_phase_b_current = (uint16_t)src_p->d2_phase_b_current;
    dst_p[2] |= pack_left_shift_u16(d2_phase_b_current, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(d2_phase_b_current, 8u, 0xffu);
    d3_phase_c_current = (uint16_t)src_p->d3_phase_c_current;
    dst_p[4] |= pack_left_shift_u16(d3_phase_c_current, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(d3_phase_c_current, 8u, 0xffu);
    d4_dc_bus_current = (uint16_t)src_p->d4_dc_bus_current;
    dst_p[6] |= pack_left_shift_u16(d4_dc_bus_current, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(d4_dc_bus_current, 8u, 0xffu);

    return (8);
}

int dbc_rms_m166_current_info::unpack(
    struct dbc_rms_m166_current_info_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t d1_phase_a_current;
    uint16_t d2_phase_b_current;
    uint16_t d3_phase_c_current;
    uint16_t d4_dc_bus_current;

    if (size < 8u) {
        return (-EINVAL);
    }

    d1_phase_a_current = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    d1_phase_a_current |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d1_phase_a_current = (int16_t)d1_phase_a_current;
    d2_phase_b_current = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    d2_phase_b_current |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->d2_phase_b_current = (int16_t)d2_phase_b_current;
    d3_phase_c_current = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    d3_phase_c_current |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->d3_phase_c_current = (int16_t)d3_phase_c_current;
    d4_dc_bus_current = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    d4_dc_bus_current |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->d4_dc_bus_current = (int16_t)d4_dc_bus_current;

    return (0);
}

int16_t dbc_rms_m166_current_info::d1_phase_a_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m166_current_info::d1_phase_a_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m166_current_info::d1_phase_a_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m166_current_info::d2_phase_b_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m166_current_info::d2_phase_b_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m166_current_info::d2_phase_b_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m166_current_info::d3_phase_c_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m166_current_info::d3_phase_c_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m166_current_info::d3_phase_c_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m166_current_info::d4_dc_bus_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m166_current_info::d4_dc_bus_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m166_current_info::d4_dc_bus_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int dbc_rms_m165_motor_position_info::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m165_motor_position_info_t *src_p,
    size_t size)
{
    uint16_t d2_motor_speed;
    uint16_t d3_electrical_output_frequency;
    uint16_t d4_delta_resolver_filtered;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->d1_motor_angle_electrical, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->d1_motor_angle_electrical, 8u, 0xffu);
    d2_motor_speed = (uint16_t)src_p->d2_motor_speed;
    dst_p[2] |= pack_left_shift_u16(d2_motor_speed, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(d2_motor_speed, 8u, 0xffu);
    d3_electrical_output_frequency = (uint16_t)src_p->d3_electrical_output_frequency;
    dst_p[4] |= pack_left_shift_u16(d3_electrical_output_frequency, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(d3_electrical_output_frequency, 8u, 0xffu);
    d4_delta_resolver_filtered = (uint16_t)src_p->d4_delta_resolver_filtered;
    dst_p[6] |= pack_left_shift_u16(d4_delta_resolver_filtered, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(d4_delta_resolver_filtered, 8u, 0xffu);

    return (8);
}

int dbc_rms_m165_motor_position_info::unpack(
    struct dbc_rms_m165_motor_position_info_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t d2_motor_speed;
    uint16_t d3_electrical_output_frequency;
    uint16_t d4_delta_resolver_filtered;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->d1_motor_angle_electrical = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->d1_motor_angle_electrical |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    d2_motor_speed = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    d2_motor_speed |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->d2_motor_speed = (int16_t)d2_motor_speed;
    d3_electrical_output_frequency = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    d3_electrical_output_frequency |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->d3_electrical_output_frequency = (int16_t)d3_electrical_output_frequency;
    d4_delta_resolver_filtered = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    d4_delta_resolver_filtered |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->d4_delta_resolver_filtered = (int16_t)d4_delta_resolver_filtered;

    return (0);
}

uint16_t dbc_rms_m165_motor_position_info::d1_motor_angle_electrical_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double dbc_rms_m165_motor_position_info::d1_motor_angle_electrical_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m165_motor_position_info::d1_motor_angle_electrical_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m165_motor_position_info::d2_motor_speed_encode(double value)
{
    return (int16_t)(value);
}

double dbc_rms_m165_motor_position_info::d2_motor_speed_decode(int16_t value)
{
    return ((double)value);
}

bool dbc_rms_m165_motor_position_info::d2_motor_speed_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m165_motor_position_info::d3_electrical_output_frequency_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m165_motor_position_info::d3_electrical_output_frequency_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m165_motor_position_info::d3_electrical_output_frequency_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m165_motor_position_info::d4_delta_resolver_filtered_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m165_motor_position_info::d4_delta_resolver_filtered_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m165_motor_position_info::d4_delta_resolver_filtered_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int dbc_rms_m164_digital_input_status::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m164_digital_input_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->d1_digital_input_1, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->d2_digital_input_2, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->d3_digital_input_3, 0u, 0x01u);
    dst_p[3] |= pack_left_shift_u8(src_p->d4_digital_input_4, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->d5_digital_input_5, 0u, 0x01u);
    dst_p[5] |= pack_left_shift_u8(src_p->d6_digital_input_6, 0u, 0x01u);
    dst_p[6] |= pack_left_shift_u8(src_p->d7_digital_input_7, 0u, 0x01u);
    dst_p[7] |= pack_left_shift_u8(src_p->d8_digital_input_8, 0u, 0x01u);

    return (8);
}

int dbc_rms_m164_digital_input_status::unpack(
    struct dbc_rms_m164_digital_input_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->d1_digital_input_1 = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->d2_digital_input_2 = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->d3_digital_input_3 = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->d4_digital_input_4 = unpack_right_shift_u8(src_p[3], 0u, 0x01u);
    dst_p->d5_digital_input_5 = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->d6_digital_input_6 = unpack_right_shift_u8(src_p[5], 0u, 0x01u);
    dst_p->d7_digital_input_7 = unpack_right_shift_u8(src_p[6], 0u, 0x01u);
    dst_p->d8_digital_input_8 = unpack_right_shift_u8(src_p[7], 0u, 0x01u);

    return (0);
}

uint8_t dbc_rms_m164_digital_input_status::d1_digital_input_1_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m164_digital_input_status::d1_digital_input_1_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m164_digital_input_status::d1_digital_input_1_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m164_digital_input_status::d2_digital_input_2_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m164_digital_input_status::d2_digital_input_2_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m164_digital_input_status::d2_digital_input_2_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m164_digital_input_status::d3_digital_input_3_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m164_digital_input_status::d3_digital_input_3_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m164_digital_input_status::d3_digital_input_3_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m164_digital_input_status::d4_digital_input_4_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m164_digital_input_status::d4_digital_input_4_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m164_digital_input_status::d4_digital_input_4_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m164_digital_input_status::d5_digital_input_5_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m164_digital_input_status::d5_digital_input_5_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m164_digital_input_status::d5_digital_input_5_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m164_digital_input_status::d6_digital_input_6_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m164_digital_input_status::d6_digital_input_6_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m164_digital_input_status::d6_digital_input_6_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m164_digital_input_status::d7_digital_input_7_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m164_digital_input_status::d7_digital_input_7_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m164_digital_input_status::d7_digital_input_7_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m164_digital_input_status::d8_digital_input_8_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m164_digital_input_status::d8_digital_input_8_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m164_digital_input_status::d8_digital_input_8_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int dbc_rms_m163_analog_input_voltages::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m163_analog_input_voltages_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->d1_analog_input_1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->d1_analog_input_1, 8u, 0x03u);
    dst_p[1] |= pack_left_shift_u16(src_p->d2_analog_input_2, 2u, 0xfcu);
    dst_p[2] |= pack_right_shift_u16(src_p->d2_analog_input_2, 6u, 0x0fu);
    dst_p[2] |= pack_left_shift_u16(src_p->d3_analog_input_3, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u16(src_p->d3_analog_input_3, 4u, 0x3fu);
    dst_p[4] |= pack_left_shift_u16(src_p->d4_analog_input_4, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->d4_analog_input_4, 8u, 0x03u);
    dst_p[5] |= pack_left_shift_u16(src_p->d5_analog_input_5, 2u, 0xfcu);
    dst_p[6] |= pack_right_shift_u16(src_p->d5_analog_input_5, 6u, 0x0fu);
    dst_p[6] |= pack_left_shift_u16(src_p->d6_analog_input_6, 4u, 0xf0u);
    dst_p[7] |= pack_right_shift_u16(src_p->d6_analog_input_6, 4u, 0x3fu);

    return (8);
}

int dbc_rms_m163_analog_input_voltages::unpack(
    struct dbc_rms_m163_analog_input_voltages_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->d1_analog_input_1 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->d1_analog_input_1 |= unpack_left_shift_u16(src_p[1], 8u, 0x03u);
    dst_p->d2_analog_input_2 = unpack_right_shift_u16(src_p[1], 2u, 0xfcu);
    dst_p->d2_analog_input_2 |= unpack_left_shift_u16(src_p[2], 6u, 0x0fu);
    dst_p->d3_analog_input_3 = unpack_right_shift_u16(src_p[2], 4u, 0xf0u);
    dst_p->d3_analog_input_3 |= unpack_left_shift_u16(src_p[3], 4u, 0x3fu);
    dst_p->d4_analog_input_4 = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->d4_analog_input_4 |= unpack_left_shift_u16(src_p[5], 8u, 0x03u);
    dst_p->d5_analog_input_5 = unpack_right_shift_u16(src_p[5], 2u, 0xfcu);
    dst_p->d5_analog_input_5 |= unpack_left_shift_u16(src_p[6], 6u, 0x0fu);
    dst_p->d6_analog_input_6 = unpack_right_shift_u16(src_p[6], 4u, 0xf0u);
    dst_p->d6_analog_input_6 |= unpack_left_shift_u16(src_p[7], 4u, 0x3fu);

    return (0);
}

uint16_t dbc_rms_m163_analog_input_voltages::d1_analog_input_1_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double dbc_rms_m163_analog_input_voltages::d1_analog_input_1_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool dbc_rms_m163_analog_input_voltages::d1_analog_input_1_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t dbc_rms_m163_analog_input_voltages::d2_analog_input_2_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double dbc_rms_m163_analog_input_voltages::d2_analog_input_2_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool dbc_rms_m163_analog_input_voltages::d2_analog_input_2_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t dbc_rms_m163_analog_input_voltages::d3_analog_input_3_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double dbc_rms_m163_analog_input_voltages::d3_analog_input_3_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool dbc_rms_m163_analog_input_voltages::d3_analog_input_3_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t dbc_rms_m163_analog_input_voltages::d4_analog_input_4_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double dbc_rms_m163_analog_input_voltages::d4_analog_input_4_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool dbc_rms_m163_analog_input_voltages::d4_analog_input_4_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t dbc_rms_m163_analog_input_voltages::d5_analog_input_5_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double dbc_rms_m163_analog_input_voltages::d5_analog_input_5_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool dbc_rms_m163_analog_input_voltages::d5_analog_input_5_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t dbc_rms_m163_analog_input_voltages::d6_analog_input_6_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double dbc_rms_m163_analog_input_voltages::d6_analog_input_6_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool dbc_rms_m163_analog_input_voltages::d6_analog_input_6_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

int dbc_rms_m162_temperature_set_3::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m162_temperature_set_3_t *src_p,
    size_t size)
{
    uint16_t d1_rtd4_temperature;
    uint16_t d2_rtd5_temperature;
    uint16_t d3_motor_temperature;
    uint16_t d4_torque_shudder;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    d1_rtd4_temperature = (uint16_t)src_p->d1_rtd4_temperature;
    dst_p[0] |= pack_left_shift_u16(d1_rtd4_temperature, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(d1_rtd4_temperature, 8u, 0xffu);
    d2_rtd5_temperature = (uint16_t)src_p->d2_rtd5_temperature;
    dst_p[2] |= pack_left_shift_u16(d2_rtd5_temperature, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(d2_rtd5_temperature, 8u, 0xffu);
    d3_motor_temperature = (uint16_t)src_p->d3_motor_temperature;
    dst_p[4] |= pack_left_shift_u16(d3_motor_temperature, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(d3_motor_temperature, 8u, 0xffu);
    d4_torque_shudder = (uint16_t)src_p->d4_torque_shudder;
    dst_p[6] |= pack_left_shift_u16(d4_torque_shudder, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(d4_torque_shudder, 8u, 0xffu);

    return (8);
}

int dbc_rms_m162_temperature_set_3::unpack(
    struct dbc_rms_m162_temperature_set_3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t d1_rtd4_temperature;
    uint16_t d2_rtd5_temperature;
    uint16_t d3_motor_temperature;
    uint16_t d4_torque_shudder;

    if (size < 8u) {
        return (-EINVAL);
    }

    d1_rtd4_temperature = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    d1_rtd4_temperature |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d1_rtd4_temperature = (int16_t)d1_rtd4_temperature;
    d2_rtd5_temperature = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    d2_rtd5_temperature |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->d2_rtd5_temperature = (int16_t)d2_rtd5_temperature;
    d3_motor_temperature = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    d3_motor_temperature |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->d3_motor_temperature = (int16_t)d3_motor_temperature;
    d4_torque_shudder = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    d4_torque_shudder |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->d4_torque_shudder = (int16_t)d4_torque_shudder;

    return (0);
}

int16_t dbc_rms_m162_temperature_set_3::d1_rtd4_temperature_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m162_temperature_set_3::d1_rtd4_temperature_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m162_temperature_set_3::d1_rtd4_temperature_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m162_temperature_set_3::d2_rtd5_temperature_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m162_temperature_set_3::d2_rtd5_temperature_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m162_temperature_set_3::d2_rtd5_temperature_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m162_temperature_set_3::d3_motor_temperature_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m162_temperature_set_3::d3_motor_temperature_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m162_temperature_set_3::d3_motor_temperature_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m162_temperature_set_3::d4_torque_shudder_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m162_temperature_set_3::d4_torque_shudder_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m162_temperature_set_3::d4_torque_shudder_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int dbc_rms_m161_temperature_set_2::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m161_temperature_set_2_t *src_p,
    size_t size)
{
    uint16_t d1_control_board_temperature;
    uint16_t d2_rtd1_temperature;
    uint16_t d3_rtd2_temperature;
    uint16_t d4_rtd3_temperature;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    d1_control_board_temperature = (uint16_t)src_p->d1_control_board_temperature;
    dst_p[0] |= pack_left_shift_u16(d1_control_board_temperature, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(d1_control_board_temperature, 8u, 0xffu);
    d2_rtd1_temperature = (uint16_t)src_p->d2_rtd1_temperature;
    dst_p[2] |= pack_left_shift_u16(d2_rtd1_temperature, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(d2_rtd1_temperature, 8u, 0xffu);
    d3_rtd2_temperature = (uint16_t)src_p->d3_rtd2_temperature;
    dst_p[4] |= pack_left_shift_u16(d3_rtd2_temperature, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(d3_rtd2_temperature, 8u, 0xffu);
    d4_rtd3_temperature = (uint16_t)src_p->d4_rtd3_temperature;
    dst_p[6] |= pack_left_shift_u16(d4_rtd3_temperature, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(d4_rtd3_temperature, 8u, 0xffu);

    return (8);
}

int dbc_rms_m161_temperature_set_2::unpack(
    struct dbc_rms_m161_temperature_set_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t d1_control_board_temperature;
    uint16_t d2_rtd1_temperature;
    uint16_t d3_rtd2_temperature;
    uint16_t d4_rtd3_temperature;

    if (size < 8u) {
        return (-EINVAL);
    }

    d1_control_board_temperature = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    d1_control_board_temperature |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d1_control_board_temperature = (int16_t)d1_control_board_temperature;
    d2_rtd1_temperature = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    d2_rtd1_temperature |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->d2_rtd1_temperature = (int16_t)d2_rtd1_temperature;
    d3_rtd2_temperature = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    d3_rtd2_temperature |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->d3_rtd2_temperature = (int16_t)d3_rtd2_temperature;
    d4_rtd3_temperature = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    d4_rtd3_temperature |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->d4_rtd3_temperature = (int16_t)d4_rtd3_temperature;

    return (0);
}

int16_t dbc_rms_m161_temperature_set_2::d1_control_board_temperature_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m161_temperature_set_2::d1_control_board_temperature_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m161_temperature_set_2::d1_control_board_temperature_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m161_temperature_set_2::d2_rtd1_temperature_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m161_temperature_set_2::d2_rtd1_temperature_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m161_temperature_set_2::d2_rtd1_temperature_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m161_temperature_set_2::d3_rtd2_temperature_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m161_temperature_set_2::d3_rtd2_temperature_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m161_temperature_set_2::d3_rtd2_temperature_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m161_temperature_set_2::d4_rtd3_temperature_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m161_temperature_set_2::d4_rtd3_temperature_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m161_temperature_set_2::d4_rtd3_temperature_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int dbc_rms_m160_temperature_set_1::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m160_temperature_set_1_t *src_p,
    size_t size)
{
    uint16_t d1_module_a;
    uint16_t d2_module_b;
    uint16_t d3_module_c;
    uint16_t d4_gate_driver_board;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    d1_module_a = (uint16_t)src_p->d1_module_a;
    dst_p[0] |= pack_left_shift_u16(d1_module_a, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(d1_module_a, 8u, 0xffu);
    d2_module_b = (uint16_t)src_p->d2_module_b;
    dst_p[2] |= pack_left_shift_u16(d2_module_b, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(d2_module_b, 8u, 0xffu);
    d3_module_c = (uint16_t)src_p->d3_module_c;
    dst_p[4] |= pack_left_shift_u16(d3_module_c, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(d3_module_c, 8u, 0xffu);
    d4_gate_driver_board = (uint16_t)src_p->d4_gate_driver_board;
    dst_p[6] |= pack_left_shift_u16(d4_gate_driver_board, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(d4_gate_driver_board, 8u, 0xffu);

    return (8);
}

int dbc_rms_m160_temperature_set_1::unpack(
    struct dbc_rms_m160_temperature_set_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t d1_module_a;
    uint16_t d2_module_b;
    uint16_t d3_module_c;
    uint16_t d4_gate_driver_board;

    if (size < 8u) {
        return (-EINVAL);
    }

    d1_module_a = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    d1_module_a |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d1_module_a = (int16_t)d1_module_a;
    d2_module_b = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    d2_module_b |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->d2_module_b = (int16_t)d2_module_b;
    d3_module_c = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    d3_module_c |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->d3_module_c = (int16_t)d3_module_c;
    d4_gate_driver_board = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    d4_gate_driver_board |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->d4_gate_driver_board = (int16_t)d4_gate_driver_board;

    return (0);
}

int16_t dbc_rms_m160_temperature_set_1::d1_module_a_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m160_temperature_set_1::d1_module_a_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m160_temperature_set_1::d1_module_a_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m160_temperature_set_1::d2_module_b_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m160_temperature_set_1::d2_module_b_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m160_temperature_set_1::d2_module_b_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m160_temperature_set_1::d3_module_c_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m160_temperature_set_1::d3_module_c_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m160_temperature_set_1::d3_module_c_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m160_temperature_set_1::d4_gate_driver_board_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m160_temperature_set_1::d4_gate_driver_board_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m160_temperature_set_1::d4_gate_driver_board_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int dbc_rms_m174_firmware_info::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m174_firmware_info_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->d1_project_code_eep_ver, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->d1_project_code_eep_ver, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->d2_sw_version, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->d2_sw_version, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->d3_date_code_mmdd, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->d3_date_code_mmdd, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->d4_date_code_yyyy, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->d4_date_code_yyyy, 8u, 0xffu);

    return (8);
}

int dbc_rms_m174_firmware_info::unpack(
    struct dbc_rms_m174_firmware_info_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->d1_project_code_eep_ver = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->d1_project_code_eep_ver |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d2_sw_version = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->d2_sw_version |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->d3_date_code_mmdd = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->d3_date_code_mmdd |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->d4_date_code_yyyy = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->d4_date_code_yyyy |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t dbc_rms_m174_firmware_info::d1_project_code_eep_ver_encode(double value)
{
    return (uint16_t)(value);
}

double dbc_rms_m174_firmware_info::d1_project_code_eep_ver_decode(uint16_t value)
{
    return ((double)value);
}

bool dbc_rms_m174_firmware_info::d1_project_code_eep_ver_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t dbc_rms_m174_firmware_info::d2_sw_version_encode(double value)
{
    return (uint16_t)(value);
}

double dbc_rms_m174_firmware_info::d2_sw_version_decode(uint16_t value)
{
    return ((double)value);
}

bool dbc_rms_m174_firmware_info::d2_sw_version_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t dbc_rms_m174_firmware_info::d3_date_code_mmdd_encode(double value)
{
    return (uint16_t)(value);
}

double dbc_rms_m174_firmware_info::d3_date_code_mmdd_decode(uint16_t value)
{
    return ((double)value);
}

bool dbc_rms_m174_firmware_info::d3_date_code_mmdd_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t dbc_rms_m174_firmware_info::d4_date_code_yyyy_encode(double value)
{
    return (uint16_t)(value);
}

double dbc_rms_m174_firmware_info::d4_date_code_yyyy_decode(uint16_t value)
{
    return ((double)value);
}

bool dbc_rms_m174_firmware_info::d4_date_code_yyyy_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int dbc_rms_m175_diag_data::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m175_diag_data_t *src_p,
    size_t size)
{
    uint16_t d3_diag_data_1;
    uint16_t d4_diag_data_2;
    uint16_t d5_diag_data_3;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->d1_buffer_record, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->d2_buffer_segment, 0u, 0xffu);
    d3_diag_data_1 = (uint16_t)src_p->d3_diag_data_1;
    dst_p[2] |= pack_left_shift_u16(d3_diag_data_1, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(d3_diag_data_1, 8u, 0xffu);
    d4_diag_data_2 = (uint16_t)src_p->d4_diag_data_2;
    dst_p[4] |= pack_left_shift_u16(d4_diag_data_2, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(d4_diag_data_2, 8u, 0xffu);
    d5_diag_data_3 = (uint16_t)src_p->d5_diag_data_3;
    dst_p[6] |= pack_left_shift_u16(d5_diag_data_3, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(d5_diag_data_3, 8u, 0xffu);

    return (8);
}

int dbc_rms_m175_diag_data::unpack(
    struct dbc_rms_m175_diag_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t d3_diag_data_1;
    uint16_t d4_diag_data_2;
    uint16_t d5_diag_data_3;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->d1_buffer_record = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->d2_buffer_segment = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    d3_diag_data_1 = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    d3_diag_data_1 |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->d3_diag_data_1 = (int16_t)d3_diag_data_1;
    d4_diag_data_2 = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    d4_diag_data_2 |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->d4_diag_data_2 = (int16_t)d4_diag_data_2;
    d5_diag_data_3 = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    d5_diag_data_3 |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->d5_diag_data_3 = (int16_t)d5_diag_data_3;

    return (0);
}

uint8_t dbc_rms_m175_diag_data::d1_buffer_record_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m175_diag_data::d1_buffer_record_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m175_diag_data::d1_buffer_record_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t dbc_rms_m175_diag_data::d2_buffer_segment_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m175_diag_data::d2_buffer_segment_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m175_diag_data::d2_buffer_segment_is_in_range(uint8_t value)
{
    return (value <= 5u);
}

int16_t dbc_rms_m175_diag_data::d3_diag_data_1_encode(double value)
{
    return (int16_t)(value);
}

double dbc_rms_m175_diag_data::d3_diag_data_1_decode(int16_t value)
{
    return ((double)value);
}

bool dbc_rms_m175_diag_data::d3_diag_data_1_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m175_diag_data::d4_diag_data_2_encode(double value)
{
    return (int16_t)(value);
}

double dbc_rms_m175_diag_data::d4_diag_data_2_decode(int16_t value)
{
    return ((double)value);
}

bool dbc_rms_m175_diag_data::d4_diag_data_2_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m175_diag_data::d5_diag_data_3_encode(double value)
{
    return (int16_t)(value);
}

double dbc_rms_m175_diag_data::d5_diag_data_3_decode(int16_t value)
{
    return ((double)value);
}

bool dbc_rms_m175_diag_data::d5_diag_data_3_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int dbc_rms_m187_u2_c_command_txd::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m187_u2_c_command_txd_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->d1_id_byte, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->d2_setpoint_calc, 0u, 0xffu);

    return (8);
}

int dbc_rms_m187_u2_c_command_txd::unpack(
    struct dbc_rms_m187_u2_c_command_txd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->d1_id_byte = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->d2_setpoint_calc = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

uint8_t dbc_rms_m187_u2_c_command_txd::d1_id_byte_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m187_u2_c_command_txd::d1_id_byte_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m187_u2_c_command_txd::d1_id_byte_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t dbc_rms_m187_u2_c_command_txd::d2_setpoint_calc_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m187_u2_c_command_txd::d2_setpoint_calc_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m187_u2_c_command_txd::d2_setpoint_calc_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int dbc_rms_m188_u2_c_message_rxd::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m188_u2_c_message_rxd_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->d1_hv_input_current_sensor_validity, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->d2_14_v_master_fault, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->d3_hv_input_current, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->d4_dtc_status, 0u, 0x07u);
    dst_p[2] |= pack_left_shift_u8(src_p->d5_dtc_index, 3u, 0xf8u);
    dst_p[3] |= pack_left_shift_u8(src_p->d6_14_v_monitor, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->d7_14_v_conditional, 7u, 0x80u);
    dst_p[6] |= pack_left_shift_u8(src_p->d8_14_v_current_monitor, 0u, 0x7fu);

    return (8);
}

int dbc_rms_m188_u2_c_message_rxd::unpack(
    struct dbc_rms_m188_u2_c_message_rxd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->d1_hv_input_current_sensor_validity = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->d2_14_v_master_fault = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->d3_hv_input_current = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->d4_dtc_status = unpack_right_shift_u8(src_p[2], 0u, 0x07u);
    dst_p->d5_dtc_index = unpack_right_shift_u8(src_p[2], 3u, 0xf8u);
    dst_p->d6_14_v_monitor = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->d7_14_v_conditional = unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    dst_p->d8_14_v_current_monitor = unpack_right_shift_u8(src_p[6], 0u, 0x7fu);

    return (0);
}

uint8_t dbc_rms_m188_u2_c_message_rxd::d1_hv_input_current_sensor_validity_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m188_u2_c_message_rxd::d1_hv_input_current_sensor_validity_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m188_u2_c_message_rxd::d1_hv_input_current_sensor_validity_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m188_u2_c_message_rxd::d2_14_v_master_fault_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m188_u2_c_message_rxd::d2_14_v_master_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m188_u2_c_message_rxd::d2_14_v_master_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m188_u2_c_message_rxd::d3_hv_input_current_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m188_u2_c_message_rxd::d3_hv_input_current_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m188_u2_c_message_rxd::d3_hv_input_current_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t dbc_rms_m188_u2_c_message_rxd::d4_dtc_status_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m188_u2_c_message_rxd::d4_dtc_status_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m188_u2_c_message_rxd::d4_dtc_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t dbc_rms_m188_u2_c_message_rxd::d5_dtc_index_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m188_u2_c_message_rxd::d5_dtc_index_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m188_u2_c_message_rxd::d5_dtc_index_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

uint8_t dbc_rms_m188_u2_c_message_rxd::d6_14_v_monitor_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m188_u2_c_message_rxd::d6_14_v_monitor_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m188_u2_c_message_rxd::d6_14_v_monitor_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t dbc_rms_m188_u2_c_message_rxd::d7_14_v_conditional_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m188_u2_c_message_rxd::d7_14_v_conditional_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m188_u2_c_message_rxd::d7_14_v_conditional_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dbc_rms_m188_u2_c_message_rxd::d8_14_v_current_monitor_encode(double value)
{
    return (uint8_t)(value);
}

double dbc_rms_m188_u2_c_message_rxd::d8_14_v_current_monitor_decode(uint8_t value)
{
    return ((double)value);
}

bool dbc_rms_m188_u2_c_message_rxd::d8_14_v_current_monitor_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

int dbc_rms_bms_current_limit::pack(
    uint8_t *dst_p,
    const struct dbc_rms_bms_current_limit_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->d1_max_discharge_current, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->d1_max_discharge_current, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->d2_max_charge_current, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->d2_max_charge_current, 8u, 0xffu);

    return (8);
}

int dbc_rms_bms_current_limit::unpack(
    struct dbc_rms_bms_current_limit_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->d1_max_discharge_current = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->d1_max_discharge_current |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d2_max_charge_current = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->d2_max_charge_current |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

uint16_t dbc_rms_bms_current_limit::d1_max_discharge_current_encode(double value)
{
    return (uint16_t)(value);
}

double dbc_rms_bms_current_limit::d1_max_discharge_current_decode(uint16_t value)
{
    return ((double)value);
}

bool dbc_rms_bms_current_limit::d1_max_discharge_current_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

uint16_t dbc_rms_bms_current_limit::d2_max_charge_current_encode(double value)
{
    return (uint16_t)(value);
}

double dbc_rms_bms_current_limit::d2_max_charge_current_decode(uint16_t value)
{
    return ((double)value);
}

bool dbc_rms_bms_current_limit::d2_max_charge_current_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

int dbc_rms_m176_fast_info::pack(
    uint8_t *dst_p,
    const struct dbc_rms_m176_fast_info_t *src_p,
    size_t size)
{
    uint16_t fast_dc_bus_voltage;
    uint16_t fast_motor_speed;
    uint16_t fast_torque_command;
    uint16_t fast_torque_feedback;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    fast_torque_command = (uint16_t)src_p->fast_torque_command;
    dst_p[0] |= pack_left_shift_u16(fast_torque_command, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(fast_torque_command, 8u, 0xffu);
    fast_torque_feedback = (uint16_t)src_p->fast_torque_feedback;
    dst_p[2] |= pack_left_shift_u16(fast_torque_feedback, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(fast_torque_feedback, 8u, 0xffu);
    fast_motor_speed = (uint16_t)src_p->fast_motor_speed;
    dst_p[4] |= pack_left_shift_u16(fast_motor_speed, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(fast_motor_speed, 8u, 0xffu);
    fast_dc_bus_voltage = (uint16_t)src_p->fast_dc_bus_voltage;
    dst_p[6] |= pack_left_shift_u16(fast_dc_bus_voltage, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(fast_dc_bus_voltage, 8u, 0xffu);

    return (8);
}

int dbc_rms_m176_fast_info::unpack(
    struct dbc_rms_m176_fast_info_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t fast_dc_bus_voltage;
    uint16_t fast_motor_speed;
    uint16_t fast_torque_command;
    uint16_t fast_torque_feedback;

    if (size < 8u) {
        return (-EINVAL);
    }

    fast_torque_command = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    fast_torque_command |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->fast_torque_command = (int16_t)fast_torque_command;
    fast_torque_feedback = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    fast_torque_feedback |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->fast_torque_feedback = (int16_t)fast_torque_feedback;
    fast_motor_speed = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    fast_motor_speed |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->fast_motor_speed = (int16_t)fast_motor_speed;
    fast_dc_bus_voltage = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    fast_dc_bus_voltage |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->fast_dc_bus_voltage = (int16_t)fast_dc_bus_voltage;

    return (0);
}

int16_t dbc_rms_m176_fast_info::fast_torque_command_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m176_fast_info::fast_torque_command_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m176_fast_info::fast_torque_command_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m176_fast_info::fast_torque_feedback_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m176_fast_info::fast_torque_feedback_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m176_fast_info::fast_torque_feedback_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m176_fast_info::fast_motor_speed_encode(double value)
{
    return (int16_t)(value);
}

double dbc_rms_m176_fast_info::fast_motor_speed_decode(int16_t value)
{
    return ((double)value);
}

bool dbc_rms_m176_fast_info::fast_motor_speed_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t dbc_rms_m176_fast_info::fast_dc_bus_voltage_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double dbc_rms_m176_fast_info::fast_dc_bus_voltage_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool dbc_rms_m176_fast_info::fast_dc_bus_voltage_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}
